import { emptyHistory, type PatientSession } from "./types";

/**
 * DEMO MODE sample patients.
 * Everything here is fabricated sample data used so the full flow works without
 * Mugen API, Azure Speech, Azure Vision, MongoDB or n8n. Always labelled in UI.
 */
const iso = (dayOffsetMinutes: number) =>
  new Date(Date.now() - dayOffsetMinutes * 60 * 1000).toISOString();

export function demoSessions(): PatientSession[] {
  return [
    {
      id: "demo_ramesh",
      queueNumber: 12,
      language: "hi",
      createdAt: iso(48),
      updatedAt: iso(46),
      status: "ready",
      demo: true,
      patient: { name: "Ramesh K.", age: 42, sex: "male", hospitalId: "OPD-2026-4412" },
      history: {
        ...emptyHistory(),
        chief_complaint: "Fever for 3 days",
        onset: "About 3 days ago",
        duration: "3 days",
        severity: "Moderate",
        progression: "Same",
        modifying_factors: "Feels better after taking paracetamol",
        associated_symptoms: ["Body ache", "Chills in the evening", "Mild headache"],
        past_medical_history: ["No previous similar episode reported"],
        current_medications: ["Paracetamol 500 mg when fever rises"],
        allergies: [],
        family_history: [],
        relevant_social_history: ["Works outdoors in dust"],
      },
      turns: [
        {
          questionId: "chief_complaint",
          questionText: {
            en: "What brings you to the doctor today?",
            hi: "आज आप डॉक्टर के पास किस समस्या के लिए आए हैं?",
          },
          answer: "तीन दिन से बुखार आ रहा है और शरीर में दर्द है",
          spoken: true,
          field: "chief_complaint",
          at: iso(48),
        },
        {
          questionId: "onset",
          questionText: { en: "When did this problem start?", hi: "यह समस्या कब शुरू हुई?" },
          answer: "तीन दिन पहले",
          spoken: true,
          field: "onset",
          at: iso(47),
        },
      ],
      documents: [
        {
          id: "demo_doc_1",
          type: "prescription",
          filename: "Prescription_12Aug2026.jpg",
          status: "extracted",
          confirmed: true,
          extracted: {
            documentDate: "12 Aug 2026",
            medicines: ["Paracetamol 500 mg — twice daily", "Cetirizine 10 mg — at night"],
            doctorName: "Dr. A. Verma, MBBS MD",
            hospitalName: "District Government Hospital, OPD",
            findings: ["Advised rest and plenty of fluids", "Review after 5 days"],
            rawText: "DISTRICT GOVT HOSPITAL / OPD SLIP 12-08-2026 ...",
            source: "OCR_EXTRACTED",
          },
        },
        {
          id: "demo_doc_2",
          type: "blood_report",
          filename: "CBC_10Aug2026.pdf",
          status: "extracted",
          confirmed: true,
          extracted: {
            documentDate: "10 Aug 2026",
            medicines: [],
            hospitalName: "City Diagnostics Laboratory",
            findings: ["Haemoglobin 11.4 g/dL", "Total WBC 11,200 /µL", "Dengue NS1: negative"],
            rawText: "CITY DIAGNOSTICS LAB CBC 10/08/2026 ...",
            source: "OCR_EXTRACTED",
          },
        },
      ],
      redFlag: { red_flag: false, rule_triggered: null, requires_human_review: false },
      summary: {
        narrative:
          "42-year-old male presenting with fever for approximately 3 days and reported body ache. Patient reports no previous similar episode. Previous prescription and blood report are available. Current medication information: paracetamol taken when fever rises. Allergies: none reported.",
        history: emptyHistory(),
        documents: [
          { type: "prescription", label: "Prescription", date: "12 Aug 2026" },
          { type: "blood_report", label: "Blood report", date: "10 Aug 2026" },
        ],
        generatedBy: "AI_STRUCTURED",
      },
      review: { reviewed: false, verifiedSections: [] },
      provenance: {
        chief_complaint: "PATIENT_REPORTED",
        onset: "PATIENT_REPORTED",
        associated_symptoms: "AI_STRUCTURED",
        current_medications: "OCR_EXTRACTED",
      },
    },
    {
      id: "demo_sunita",
      queueNumber: 13,
      language: "hi",
      createdAt: iso(30),
      updatedAt: iso(28),
      status: "ready",
      demo: true,
      patient: { name: "Sunita P.", age: 56, sex: "female", hospitalId: "OPD-2026-4415" },
      history: {
        ...emptyHistory(),
        chief_complaint: "Knee pain, both knees, for 6 months",
        onset: "About 6 months ago",
        duration: "6 months",
        severity: "Moderate",
        progression: "Worse",
        modifying_factors: "Worse on climbing stairs, better with rest",
        associated_symptoms: ["Stiffness in the morning", "Mild swelling of right knee"],
        past_medical_history: ["High blood pressure reported for 4 years"],
        current_medications: ["Amlodipine 5 mg — once daily"],
        allergies: ["Reported reaction to sulfa medicines"],
        family_history: ["Mother had joint pain"],
        relevant_social_history: [],
      },
      turns: [],
      documents: [
        {
          id: "demo_doc_3",
          type: "imaging_report",
          filename: "Xray_knee_02Jul2026.jpg",
          status: "extracted",
          confirmed: true,
          extracted: {
            documentDate: "02 Jul 2026",
            medicines: [],
            hospitalName: "Radiology Department",
            findings: ["X-ray right knee: reported joint space narrowing", "No fracture reported"],
            rawText: "X-RAY RIGHT KNEE AP/LAT 02-07-2026 ...",
            source: "OCR_EXTRACTED",
          },
        },
      ],
      redFlag: { red_flag: false, rule_triggered: null, requires_human_review: false },
      review: { reviewed: false, verifiedSections: [] },
      provenance: { chief_complaint: "PATIENT_REPORTED", allergies: "PATIENT_REPORTED" },
    },
    {
      id: "demo_amit",
      queueNumber: 14,
      language: "en",
      createdAt: iso(12),
      updatedAt: iso(10),
      status: "needs_review",
      demo: true,
      patient: { name: "Amit S.", age: 67, sex: "male", phone: "98XXXXXX21" },
      history: {
        ...emptyHistory(),
        chief_complaint: "Cough for 5 days with chest pain",
        onset: "5 days ago",
        duration: "5 days",
        severity: "Severe",
        progression: "Worse",
        modifying_factors: "Worse at night",
        associated_symptoms: ["Chest pain while coughing", "Shortness of breath on walking", "Low fever"],
        past_medical_history: ["Reported smoking for many years", "Diabetes reported for 10 years"],
        current_medications: ["Metformin 500 mg — twice daily"],
        allergies: [],
        family_history: [],
        relevant_social_history: ["Tobacco use reported"],
      },
      turns: [],
      documents: [
        {
          id: "demo_doc_4",
          type: "discharge_summary",
          filename: "Discharge_18Mar2026.pdf",
          status: "extracted",
          confirmed: true,
          extracted: {
            documentDate: "18 Mar 2026",
            medicines: ["Metformin 500 mg — twice daily"],
            doctorName: "Dr. S. Nair",
            hospitalName: "Government Medical College Hospital",
            findings: ["Admitted 14–18 Mar 2026", "Discharged in stable condition"],
            rawText: "GMCH DISCHARGE SUMMARY ...",
            source: "OCR_EXTRACTED",
          },
        },
      ],
      redFlag: {
        red_flag: true,
        rule_triggered: "RF_CHEST_PAIN_SEVERE",
        requires_human_review: true,
        detected_at: iso(11),
      },
      review: { reviewed: false, verifiedSections: [] },
      provenance: { chief_complaint: "PATIENT_REPORTED", current_medications: "OCR_EXTRACTED" },
    },
  ];
}
