/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as DoctorQueueRouteImport } from './routes/doctor/queue'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor/patients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => DoctorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/doctor' | '/doctor/queue' | '/doctor/' | '/doctor/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doctor/queue' | '/doctor' | '/doctor/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/doctor/queue'
    | '/doctor/'
    | '/doctor/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/patients/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
  }
}

interface DoctorRouteRouteChildren {
  DoctorQueueRoute: typeof DoctorQueueRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorQueueRoute: DoctorQueueRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
