/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as DoctorQueueRouteImport } from './routes/doctor/queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorQueueRoute = DoctorQueueRouteImport.update({
  id: '/doctor/queue',
  path: '/doctor/queue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor': typeof DoctorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor/queue': typeof DoctorQueueRoute
  '/doctor/': typeof DoctorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doctor/queue' | '/doctor/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doctor/queue' | '/doctor'
  id: '__root__' | '/' | '/doctor/queue' | '/doctor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorQueueRoute: typeof DoctorQueueRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/queue': {
      id: '/doctor/queue'
      path: '/doctor/queue'
      fullPath: '/doctor/queue'
      preLoaderRoute: typeof DoctorQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorQueueRoute: DoctorQueueRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
